apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: digitalocean
provisioner: digitalocean

## volumeBindingMode controls when volume binding and dynamic provisioning should occur. The Immediate mode indicates that volume
## binding and dynamic provisioning occurs once the PersistentVolumeClaim is created.
volumeBindingMode: Immediate